### ISSUE TITLE
Swiping on an appointment/reminder

### ISSUE THREAD

**Issue by rml9ty** [nicho1asdev/Dyadic-Support#3]
An appointment or reminders opens, as if you simply tapped it, when trying to switch back to toggles by swiping on the appointment. (I hope this makes sense.)

I‘m swiping on the appointment called ‚Jens‘, not tapping it. https://imgur.com/a/usOfNE6

**Comment by nicho1asdev** [comment]
Yeah I'm aware of that and have tried to fix it, will see what I can do about it.
