### ISSUE TITLE
[Feature requests] Please add "swipe down from top left" gesture for widget page!

### ISSUE THREAD

**Issue by zuiaiqie** [nicho1asdev/Dyadic-Support#5]
As requested [here ](https://www.reddit.com/r/jailbreak/comments/fnjzs1/release_dyadic_a_cleaner_interface_why_have_the/fla2olm/), please add “swipe down from top left” gesture for widget page!

**Comment by nicho1asdev** [comment]
This feature is added in Dyadic v1.1 :). Closing request.
